### PR TITLE
Added support for multiple languages

### PR DESCRIPTION
**Pull request by alexpennells**
Addresses issue #4

### CODE REVIEW

**Comment by tyler-vincent** [comment]
Didn't update README.md what a worthless PR

**Comment by hsxu** [comment]
THERE ARE TWO UNNECESSARY SPACES NOW

**Comment by alexpennells** [comment]
Added update to README. Plz merge ASAP, ty

**Comment by tyler-vincent** [comment]
This is not MLP license gtfo

**Comment by alexpennells** [comment]
This good change. Plz add. ty.

**Comment by masterful** [comment]
hi i am having problems with the console shows nothing when I load the page on the windows, it does not show sent the message. Thank you

**Comment by alexpennells** [comment]
you load windows wrong, come back after get education on MLP

**Pull request closed without merging**
